name: Build & Release on PR Merge

on:
  pull_request:
    types:
      - closed
    branches: 
      - main
  workflow_dispatch:
    

jobs:
  draft_release:
    permissions:
      contents: write
    name: Create GitHub Release
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create_release.outputs.id }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Bump version and push tag
      id: tag
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Bump package.json version
      id: npm-version
      uses: reedyuk/npm-version@1.2.1
      with:
        version: ${{ steps.tag.outputs.new_version }}

    - name: Commit semver changes to repo
      uses: stefanzweifel/git-auto-commit-action@v4.16.0


    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
      with:
        tag_name: ${{ steps.tag.outputs.new_tag }}
        release_name: ${{ steps.tag.outputs.new_tag }}
        body: ${{ steps.tag.outputs.changelog }}
        draft: true
        prerelease: false

  build_windows:
    needs: [draft_release]
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      
      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run make

      - name: Log the build output
        run: ls out/make -R

      - name: Upload Build As Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Sourcepool Server for Windows 64-bit
          path: out/make/squirrel.windows/x64/*.exe

      - name: Upload Build to Release
        uses: softprops/action-gh-release@v1
        with:
          files: out/make/squirrel.windows/x64/*.exe
          tag_name: ${{ needs.draft_release.outputs.release_id }}
          draft: true
  
  make_release:
    needs: [draft_release, build_windows]
    name: Make release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@v3

    - name: Mark release as published
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ needs.draft_release.outputs.release_id }}
        draft: false
        
