name: Generate Release with Changelog on PR Merge

on:
  pull_request:
    types:
      - closed
    branches: 
      - main
  workflow_dispatch:
    

jobs:
  on_pr_merge:
    if: github.event.pull_request.merged == true
    name: On PR Merge
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged

    - name: Checkout GitHub Action
      uses: actions/checkout@v3

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        release_name: ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}